// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package todoDB

type List struct {
	ID     int64
	Todo   string
	Userid int64
}

type User struct {
	ID       int64
	Email    string
	Password string
}
